交通部公開全台公共自行車站位資料，每個站都有站名、地址、縣市、可停放自行車總容量與經緯度。

請利用 Pandas 整理資料，找出不同縣市有哪些大型站點，並輸出整理結果。

- 資料集名稱：[公共自行車租借站位資訊](https://data.gov.tw/dataset/177482)


請完成：
- 顯示前 10 筆資料。
- 顯示共有幾筆站點資料。
- 查看有哪些欄位。
- 查看每個欄位資料型態。
- 找出地址包含「復興南路」的站點
- 找出容量超過 90 台的站點。
- 新增「大型站點」欄位 (容量 ≥ 70 為「是」)。
- 將所有大型站點輸出成 大型YouBike站點.csv。

### 下載資料

In [1]:
import requests
import pandas as pd


### 設定 API 網址
url = "https://tdx.transportdata.tw/api/basic/v2/Bike/Station/City/Taipei?$format=JSON"

headers = {
    "User-Agent": "Mozilla/5.0"
}


### 發送 HTTP 請求
response = requests.get(url, headers=headers, timeout=30)
response.raise_for_status() # 如果請求失敗 (4xx、5xx)，直接拋出例外

print("狀態碼：", response.status_code)


### 將 JSON 轉換成 Python 資料
data = response.json()

print("\n資料筆數：")
print(len(data))


### 將 JSON 轉換成 DataFrame
df = pd.json_normalize(data)
df

狀態碼： 200

資料筆數：
1800

,StationUID,StationID,AuthorityID,BikesCapacity,ServiceType,SrcUpdateTime,UpdateTime,StationName.Zh_tw,StationName.En,StationPosition.PositionLon,StationPosition.PositionLat,StationPosition.GeoHash,StationAddress.Zh_tw,StationAddress.En
0,TPE500101001,500101001,TPE,28,2,2026-09-09T23:38:03+08:00,2026-09-09T23:38:41+08:00,YouBike2.0_捷運科技大樓站,YouBike2.0_MRT Technology Bldg. Sta.,121.54360,25.02605,wsqqmgc77,復興南路二段235號前,"No.235, Sec. 2, Fuxing S. Rd."
1,TPE500101002,500101002,TPE,21,2,2026-09-09T23:38:03+08:00,2026-09-09T23:38:41+08:00,YouBike2.0_復興南路二段273號前,"YouBike2.0_No.273, Sec. 2, Fuxing S. Rd.",121.54357,25.02565,wsqqmgc2f,復興南路二段273號西側,"No.273, Sec. 2, Fuxing S. Rd. (West)"
2,TPE500101003,500101003,TPE,28,2,2026-09-09T23:38:03+08:00,2026-09-09T23:38:41+08:00,YouBike2.0_國北教大實小東側門,YouBike2.0_NTUE Experiment Elementary School (...,121.54124,25.02429,wsqqmex9h,和平東路二段96巷7號,"No. 7, Ln. 96, Sec. 2, Heping E. Rd"
3,TPE500101004,500101004,TPE,11,2,2026-09-09T23:38:03+08:00,2026-09-09T23:38:41+08:00,YouBike2.0_和平公園東側,YouBike2.0_Heping Park (East),121.54282,25.02351,wsqqmg2u8,和平東路二段118巷33號,"No. 33, Ln. 118, Sec. 2, Heping E. Rd"
4,TPE500101005,500101005,TPE,16,2,2026-09-09T23:38:03+08:00,2026-09-09T23:38:41+08:00,YouBike2.0_辛亥復興路口西北側,YouBike2.0_Xinhai Fuxing Rd. Intersection (Nor...,121.54299,25.02153,wsqqmg0bu,復興南路二段368號,"No. 368, Sec. 2, Fuxing S. Rd."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1795,TPE500119099,500119099,TPE,36,2,2026-09-09T23:38:03+08:00,2026-09-09T23:38:41+08:00,YouBike2.0_臺大博理館北側,YouBike2.0_NTU Barry Lam Hall(North),121.54245,25.01945,wsqqmf8sb,臺大博理館北側,NTU Barry Lam Hall(North)
1796,TPE500119100,500119100,TPE,24,2,2026-09-09T23:38:03+08:00,2026-09-09T23:38:41+08:00,YouBike2.0_臺大博理館東側,YouBike2.0_NTU Barry Lam Hall(East),121.54264,25.01929,wsqqmf8eu,臺大博理館東側,NTU Barry Lam Hall(North)
1797,TPE500119101,500119101,TPE,56,2,2026-09-09T23:38:03+08:00,2026-09-09T23:38:41+08:00,YouBike2.0_臺大德田館東北側,YouBike2.0_NTU Der Tian Hall (Northeast),121.54197,25.01976,wsqqmf8nt,臺大德田館東北側,NTU Der Tian Hall (Northeast)
1798,TPE500119102,500119102,TPE,42,2,2026-09-09T23:38:03+08:00,2026-09-09T23:38:41+08:00,YouBike2.0_臺大普通教學館東側,YouBike2.0_NTU Putong Lecture Building (East),121.53717,25.01861,wsqqmdkxv,臺大普通教學館東側,NTU Putong Lecture Building (East)
1799,TPE500119103,500119103,TPE,34,2,2026-09-09T23:38:03+08:00,2026-09-09T23:38:41+08:00,YouBike2.0_臺大次震宇宙館西側,YouBike2.0_NTU Cosmology Hall (West),121.53700,25.02162,wsqqmeh99,臺大次震宇宙館西側,NTU Cosmology Hall (West)

### 顯示前 10 筆資料

In [4]:
df.head(10)

,StationUID,StationID,AuthorityID,BikesCapacity,ServiceType,SrcUpdateTime,UpdateTime,StationName.Zh_tw,StationName.En,StationPosition.PositionLon,StationPosition.PositionLat,StationPosition.GeoHash,StationAddress.Zh_tw,StationAddress.En
0,TPE500101001,500101001,TPE,28,2,2026-09-09T23:38:03+08:00,2026-09-09T23:38:41+08:00,YouBike2.0_捷運科技大樓站,YouBike2.0_MRT Technology Bldg. Sta.,121.54360,25.02605,wsqqmgc77,復興南路二段235號前,"No.235, Sec. 2, Fuxing S. Rd."
1,TPE500101002,500101002,TPE,21,2,2026-09-09T23:38:03+08:00,2026-09-09T23:38:41+08:00,YouBike2.0_復興南路二段273號前,"YouBike2.0_No.273, Sec. 2, Fuxing S. Rd.",121.54357,25.02565,wsqqmgc2f,復興南路二段273號西側,"No.273, Sec. 2, Fuxing S. Rd. (West)"
2,TPE500101003,500101003,TPE,28,2,2026-09-09T23:38:03+08:00,2026-09-09T23:38:41+08:00,YouBike2.0_國北教大實小東側門,YouBike2.0_NTUE Experiment Elementary School (...,121.54124,25.02429,wsqqmex9h,和平東路二段96巷7號,"No. 7, Ln. 96, Sec. 2, Heping E. Rd"
3,TPE500101004,500101004,TPE,11,2,2026-09-09T23:38:03+08:00,2026-09-09T23:38:41+08:00,YouBike2.0_和平公園東側,YouBike2.0_Heping Park (East),121.54282,25.02351,wsqqmg2u8,和平東路二段118巷33號,"No. 33, Ln. 118, Sec. 2, Heping E. Rd"
4,TPE500101005,500101005,TPE,16,2,2026-09-09T23:38:03+08:00,2026-09-09T23:38:41+08:00,YouBike2.0_辛亥復興路口西北側,YouBike2.0_Xinhai Fuxing Rd. Intersection (Nor...,121.54299,25.02153,wsqqmg0bu,復興南路二段368號,"No. 368, Sec. 2, Fuxing S. Rd."
5,TPE500101006,500101006,TPE,27,2,2026-09-09T23:38:03+08:00,2026-09-09T23:38:41+08:00,YouBike2.0_復興南路二段280號前,"YouBike2.0_No. 280, Sec. 2, Fuxing S. Rd.",121.54328,25.02429,wsqqmg915,復興南路二段280號,"No. 280, Sec. 2, Fuxing S. Rd."
6,TPE500101007,500101007,TPE,11,2,2026-09-09T23:38:03+08:00,2026-09-09T23:38:41+08:00,YouBike2.0_復興南路二段340巷口,"YouBike2.0_Ln. 340, Sec. 2, Fuxing S. Rd.",121.54326,25.02253,wsqqmg1ng,復興南路二段342號,"No. 342, Sec. 2, Fuxing S. Rd."
7,TPE500101008,500101008,TPE,17,2,2026-09-09T23:38:03+08:00,2026-09-09T23:38:41+08:00,YouBike2.0_新生南路三段52號前,"YouBike2.0_No. 52, Sec. 3, Xinsheng S. Rd.",121.53407,25.02112,wsqqmdfqt,新生南路三段52號,"No. 52, Sec. 3, Xinsheng S. Rd."
8,TPE500101009,500101009,TPE,16,2,2026-09-09T23:38:03+08:00,2026-09-09T23:38:41+08:00,YouBike2.0_新生南路三段66號前,"YouBike2.0_No. 66, Sec. 3, Xinsheng S. Rd.",121.53384,25.01976,wsqqmddnx,新生南路三段66號東側,"No. 66, Sec. 3, Xinsheng S. Rd. (East)"
9,TPE500101010,500101010,TPE,20,2,2026-09-09T23:38:03+08:00,2026-09-09T23:38:41+08:00,YouBike2.0_新生南路三段82號前,"YouBike2.0_No. 82, Sec. 3, Xinsheng S. Rd.",121.53361,25.01894,wsqqmdd1f,新生南路三段82號,"No. 82, Sec. 3, Xinsheng S. Rd."

### 顯示共有幾筆站點資料

In [6]:
df.shape

(1800, 14)

### 查看有哪些欄位

In [7]:
df.columns

Index(['StationUID', 'StationID', 'AuthorityID', 'BikesCapacity',
       'ServiceType', 'SrcUpdateTime', 'UpdateTime', 'StationName.Zh_tw',
       'StationName.En', 'StationPosition.PositionLon',
       'StationPosition.PositionLat', 'StationPosition.GeoHash',
       'StationAddress.Zh_tw', 'StationAddress.En'],
      dtype='str')

### 查看每個欄位資料型態

In [8]:
df.dtypes

StationUID                         str
StationID                          str
AuthorityID                        str
BikesCapacity                    int64
ServiceType                      int64
SrcUpdateTime                      str
UpdateTime                         str
StationName.Zh_tw                  str
StationName.En                     str
StationPosition.PositionLon    float64
StationPosition.PositionLat    float64
StationPosition.GeoHash            str
StationAddress.Zh_tw               str
StationAddress.En                  str
dtype: object

### 找出地址包含「復興南路」的站點

In [ ]:
### 找出地址包含「復興南路」的站點
Fuxing = df.loc[
    df["StationAddress.Zh_tw"].str.contains(
        "復興南路",
        na=False # 如果遇到缺失值 NaN，就把它當成「沒有符合條件」(False)
    )
]

Fuxing

,StationUID,StationID,AuthorityID,BikesCapacity,ServiceType,SrcUpdateTime,UpdateTime,StationName.Zh_tw,StationName.En,StationPosition.PositionLon,StationPosition.PositionLat,StationPosition.GeoHash,StationAddress.Zh_tw,StationAddress.En
0,TPE500101001,500101001,TPE,28,2,2026-09-09T23:38:03+08:00,2026-09-09T23:38:41+08:00,YouBike2.0_捷運科技大樓站,YouBike2.0_MRT Technology Bldg. Sta.,121.54360,25.02605,wsqqmgc77,復興南路二段235號前,"No.235, Sec. 2, Fuxing S. Rd."
1,TPE500101002,500101002,TPE,21,2,2026-09-09T23:38:03+08:00,2026-09-09T23:38:41+08:00,YouBike2.0_復興南路二段273號前,"YouBike2.0_No.273, Sec. 2, Fuxing S. Rd.",121.54357,25.02565,wsqqmgc2f,復興南路二段273號西側,"No.273, Sec. 2, Fuxing S. Rd. (West)"
4,TPE500101005,500101005,TPE,16,2,2026-09-09T23:38:03+08:00,2026-09-09T23:38:41+08:00,YouBike2.0_辛亥復興路口西北側,YouBike2.0_Xinhai Fuxing Rd. Intersection (Nor...,121.54299,25.02153,wsqqmg0bu,復興南路二段368號,"No. 368, Sec. 2, Fuxing S. Rd."
5,TPE500101006,500101006,TPE,27,2,2026-09-09T23:38:03+08:00,2026-09-09T23:38:41+08:00,YouBike2.0_復興南路二段280號前,"YouBike2.0_No. 280, Sec. 2, Fuxing S. Rd.",121.54328,25.02429,wsqqmg915,復興南路二段280號,"No. 280, Sec. 2, Fuxing S. Rd."
6,TPE500101007,500101007,TPE,11,2,2026-09-09T23:38:03+08:00,2026-09-09T23:38:41+08:00,YouBike2.0_復興南路二段340巷口,"YouBike2.0_Ln. 340, Sec. 2, Fuxing S. Rd.",121.54326,25.02253,wsqqmg1ng,復興南路二段342號,"No. 342, Sec. 2, Fuxing S. Rd."
11,TPE500101013,500101013,TPE,9,2,2026-09-09T23:38:03+08:00,2026-09-09T23:38:41+08:00,YouBike2.0_和平復興路口西北側,YouBike2.0_Heping Fuxing Rd. Intersection (Nor...,121.54332,25.02543,wsqqmg9ps,復興南路二段236號,"No. 236, Sec. 2, Fuxing S. Rd."
35,TPE500101038,500101038,TPE,27,2,2026-09-09T23:38:03+08:00,2026-09-09T23:38:41+08:00,YouBike2.0_臺大社科院圖書館前,YouBike2.0_NTU College of social Sciences Buil...,121.54284,25.02101,wsqqmfbvc,辛亥路與復興南路口西南側,Xinhai Fuxing Rd. Intersection (Southwest)
76,TPE500101131,500101131,TPE,50,2,2026-09-09T23:38:03+08:00,2026-09-09T23:38:41+08:00,YouBike2.0_復興南路1段340巷口,"YouBike2.0_Ln. 340, Sec. 1, Fuxing S. Rd Inter...",121.54348,25.03701,wsqqmvc70,復興南路一段信義路三段147巷45弄口,"Sec. 1, Fuxing S. Rd & Aly. 45, Ln. 147, Sec. ..."
78,TPE500101133,500101133,TPE,29,2,2026-09-09T23:38:03+08:00,2026-09-09T23:38:41+08:00,YouBike2.0_捷運忠孝復興站(2號出口),YouBike2.0_MRT Zhongxiao Fuxing Sta (Exit 2),121.54360,25.04035,wsqqmy3qe,復興南路一段/仁愛路三段123巷13弄(西北側),"Sec. 1, Fuxing S. R & Aly. 13, Ln. 123, Sec. 3..."
96,TPE500101151,500101151,TPE,23,2,2026-09-09T23:38:03+08:00,2026-09-09T23:38:41+08:00,YouBike2.0_大安高工,YouBike2.0_Daan Vocational High School,121.54339,25.03126,wsqqmuc1w,復興南路二段52號(前),"No. 52, Sec. 2, Fuxing S. Rd."
104,TPE500101159,500101159,TPE,30,2,2026-09-09T23:38:03+08:00,2026-09-09T23:38:41+08:00,YouBike2.0_捷運忠孝復興站(5號出口),YouBike2.0_MRT Zhongxiao Fuxing Sta (Exit 5),121.54407,25.04253,wsqqmyceq,復興南路一段135巷口,"No. 3, Ln. 135, Sec. 1, Fuxing S. Rd. (Opposite)"
118,TPE500101174,500101174,TPE,31,2,2026-09-09T23:38:03+08:00,2026-09-09T23:38:41+08:00,YouBike2.0_復興南路二段128巷口,"YouBike2.0_Ln. 128, Sec. 2, Fuxing S. Rd.",121.54336,25.02861,wsqqmu34j,復興南路二段142之1號前,"No. 142-1, Sec. 2, Fusing S. Rd."
121,TPE500101177,500101177,TPE,15,2,2026-09-09T23:38:03+08:00,2026-09-09T23:38:41+08:00,YouBike2.0_復興南路一段126巷口,"YouBike2.0_Ln. 126, Sec. 1, Fuxing S. Rd.",121.54313,25.04311,wsqqmycn8,復興南路一段126巷1號前,"No. 1, Ln. 126, Sec. 1, Fuxing S. Rd."
128,TPE500101186,500101186,TPE,29,2,2026-09-09T23:38:03+08:00,2026-09-09T23:38:41+08:00,YouBike2.0_捷運大安站(6號出口),YouBike2.0_MRT Da’an Sta. (Exit 6),121.54376,25.03479,wsqqmv3qn,復興南路一段303號前,"No. 303, Sec. 1, Fuxing S. Rd."
158,TPE500101217,500101217,TPE,26,2,2026-09-09T23:38:03+08:00,2026-09-09T23:38:41+08:00,YouBike2.0_捷運大安站(5號出口),YouBike2.0_MRT Da’an Sta. (Exit 5),121.54372,25.03303,wsqqmv17v,復興南路二段/信義路四段(東南側),"Sec. 2, Fuxing S. Rd. & Sec. 4, Xinyi Rd. Inte..."
167,TPE500101227,500101227,TPE,28,2,2026-09-09T23:38:03+08:00,2026-09-09T23:38:41+08:00,YouBike2.0_復興忠孝東路口(東南側),YouBike2.0_Zhongxiao E. Rd. & Fuxing S. Rd. In...,121.54389,25.04061,wsqqmy981,復興南路一段191號前,"No. 191, Sec. 1, Fuxing S. Rd."
189,TPE500101250,500101250,TPE,32,2,2026-09-09T23:38:03+08:00,2026-09-09T23:38:41+08:00,YouBike2.0_國立臺北教育大學創意館,YouBike2.0_NTUE Creative Building,121.54394,25.02305,wsqqmg39g,復興南路二段337巷6弄14號對側,"No. 14, Aly. 6, Ln. 337, Sec. 2, FuXing S. Rd."
196,TPE500101257,500101257,TPE,20,2,2026-09-09T23:38:03+08:00,2026-09-09T23:38:41+08:00,YouBike2.0_龍圖公園,YouBike2.0_Longtu Park,121.54184,25.03050,wsqqmu8j4,復興南路二段78巷42弄5號對面,"No. 5, Aly. 42, Ln. 78, Sec. 2, FuXing S. Rd. ..."
212,TPE500101274,500101274,TPE,72,2,2026-09-09T23:38:03+08:00,2026-09-09T23:38:41+08:00,YouBike2.0_捷運科技大樓站(2號出口),YouBike2.0_MRT Technology Building. Sta. (Exi...,121.54328,25.02592,wsqqmgc4e,復興南路二段224號,"No. 224, Sec. 2, FuXing S. Rd."
725,TPE500107012,500107012,TPE,52,2,2026-09-09T23:38:03+08:00,2026-09-09T23:38:41+08:00,YouBike2.0_復興市民路口,YouBike2.0_Fuxing Rd. & Civic Blvd. Intersection,121.54375,25.04585,wsqqmz3qw,復興南路一段36-9號前人行道,"No. 36-9, Sec. 1, Fuxing S. Rd."

### 找出容量超過 90 台的站點

In [25]:
large_station = df.loc[
    df["BikesCapacity"] >= 90,
]
large_station

,StationUID,StationID,AuthorityID,BikesCapacity,ServiceType,SrcUpdateTime,UpdateTime,StationName.Zh_tw,StationName.En,StationPosition.PositionLon,StationPosition.PositionLat,StationPosition.GeoHash,StationAddress.Zh_tw,StationAddress.En
19,TPE500101022,500101022,TPE,99,2,2026-09-09T23:38:03+08:00,2026-09-09T23:38:41+08:00,YouBike2.0_捷運公館站(2號出口),YouBike2.0_MRT Gongguan Sta. (Exit 2),121.53438,25.01491,wsqqm9fdk,捷運公館站(2號出口)外側,MRT Gongguan Sta. (Exit 2)
22,TPE500101025,500101025,TPE,97,2,2026-09-09T23:38:03+08:00,2026-09-09T23:38:41+08:00,YouBike2.0_臺灣科技大學側門,YouBike2.0_NTUST(Side Gate),121.53973,25.01295,wsqqm9qwb,基隆路四段73巷與基隆路口,"Ln. 73, Sec. 4, Keelung Rd. Intersection"
24,TPE500101027,500101027,TPE,99,2,2026-09-09T23:38:03+08:00,2026-09-09T23:38:41+08:00,YouBike2.0_臺灣科技大學後門,YouBike2.0_NTUST(Back Gate),121.54165,25.01182,wsqqm9rbm,基隆路四段41巷68弄臺科帆船大樓旁,"Aly. 68, Ln. 41, Sec. 4, Keelung Rd."
59,TPE500101113,500101113,TPE,99,2,2026-09-09T23:38:03+08:00,2026-09-09T23:38:41+08:00,YouBike2.0_臺北市立圖書館(總館),YouBike2.0_Taipei Public library,121.53790,25.02895,wsqqmsmhn,建國南路二段/建國南路二段151巷(橋下空間),"Sec. 2, Jianguo S. Rd & Ln. 151, Sec. 2, Jiang..."
124,TPE500101181,500101181,TPE,99,2,2026-09-09T23:38:03+08:00,2026-09-09T23:38:41+08:00,YouBike2.0_捷運公館站(3號出口),YouBike2.0_MRT Gongguan Sta.(Exit.3),121.53374,25.01551,wsqqm9fjv,捷運公館站(3號出口)西側,MRT Gongguan Sta.(Exit.3)(West)
623,TPE500106055,500106055,TPE,99,2,2026-09-09T23:38:03+08:00,2026-09-09T23:38:41+08:00,YouBike2.0_臺北市立大學(博愛校區),YouBike2.0_University of Taipei Boai Campus,121.51327,25.03545,wsqqmje60,愛國西路1號(前),"No. 1, Aiguo W. Rd."
625,TPE500106057,500106057,TPE,98,2,2026-09-09T23:38:03+08:00,2026-09-09T23:38:41+08:00,YouBike2.0_市民金山路口,YouBike2.0_Civic Blvd & Jinshan N. Rd Intersec...,121.53068,25.04590,wsqqmrryy,金山市民大道口南側,Jinshan N. Rd & Civic Blvd Intersection. (South)
1155,TPE500109011,500109011,TPE,99,2,2026-09-09T23:38:03+08:00,2026-09-09T23:38:41+08:00,YouBike2.0_捷運關渡站(1號出口),YouBike2.0_MRT Guandu Sta. (Exit 1),121.46712,25.12397,wsqquj9tt,大度路三段270巷/立功街55巷(西南側),"Ln. 270, Sec. 3, Dadu Rd. & Ln. 55, Ligong St...."
1240,TPE500109101,500109101,TPE,99,2,2026-09-09T23:38:03+08:00,2026-09-09T23:38:41+08:00,YouBike2.0_關渡碼頭,YouBike2.0_Guandu Wharf,121.46228,25.12066,wsqqgvn4k,關渡碼頭東南側,Guandu Wharf (Southeast)
1541,TPE500112035,500112035,TPE,90,2,2026-09-09T23:38:03+08:00,2026-09-09T23:38:41+08:00,YouBike2.0_信義廣場(台北101),YouBike2.0_Xinyi Plaza (Taipei 101),121.56620,25.03306,wsqqqm1u1,松智路/信義路(東北側),Songzhi Rd & Xinyi Rd Intersection. (Northeast)
1588,TPE500112085,500112085,TPE,92,2,2026-09-09T23:38:03+08:00,2026-09-09T23:38:41+08:00,YouBike2.0_捷運市政府站(3號出口),YouBike2.0_MRT Taipei City Hall Sta. (Exit 3),121.56789,25.04084,wsqqqqe13,忠孝東路/松仁路(東南側),Zhongxiao E. Rd. & Songren Rd. Intersection (S...
1667,TPE500113034,500113034,TPE,94,2,2026-09-09T23:38:03+08:00,2026-09-09T23:38:41+08:00,YouBike2.0_開封西寧路口,YouBike2.0_Kaifeng St. & Xining Rd. Intersection,121.50717,25.04662,wsqqkzwg4,西寧南路12號(對面),"No. 12, Xining Rd. (Opposite)"
1671,TPE500113038,500113038,TPE,99,2,2026-09-09T23:38:03+08:00,2026-09-09T23:38:41+08:00,YouBike2.0_西本願寺廣場,YouBike2.0_Nishi Honganji Relics Plaza,121.50769,25.04099,wsqqkyx4q,中華路一段164號(前),"No. 164-1, Sec. 1, Zhonghua Rd."
1736,TPE500119006,500119006,TPE,92,2,2026-09-09T23:38:03+08:00,2026-09-09T23:38:41+08:00,YouBike2.0_臺大卓越研究大樓,YouBike2.0_NTU Complex for Research Excellence,121.52917,25.01466,wsqqm3ybf,臺大水源舍區C南側,NTU Prince House Chang Hsing Dorms C(South)
1773,TPE500119077,500119077,TPE,99,2,2026-09-09T23:38:03+08:00,2026-09-09T23:38:41+08:00,YouBike2.0_臺大博雅館西側,YouBike2.0_NTU Liberal Education Classroom Bui...,121.53600,25.01890,wsqqmdecd,臺大博雅館西側,NTU Liberal Education Classroom Building(West)
1787,TPE500119091,500119091,TPE,93,2,2026-09-09T23:38:03+08:00,2026-09-09T23:38:41+08:00,YouBike2.0_臺大明達館北側(員工宿舍),YouBike2.0_NTU Ming - Da Hall (Staff Dormitory),121.54469,25.01816,wsqqmf6jk,明達館北側前空地,NTU Ming - Da Hall (North)
1792,TPE500119096,500119096,TPE,99,2,2026-09-09T23:38:03+08:00,2026-09-09T23:38:41+08:00,YouBike2.0_臺大水源舍區C棟,YouBike2.0_NTU Shui-Yuan Dorms C,121.52892,25.01547,wsqqm3ytt,臺大水源舍區C棟西側,NTU Shui-Yuan Dorms C (West)

### 新增「大型站點」欄位 (容量 ≥ 70 為「是」)。

In [26]:
### 新增大型站點欄位
df["大型站點"] = "否"

df.loc[
    df["BikesCapacity"] >= 70,
    "大型站點"
] = "是"

### 將所有大型站點輸出成 大型YouBike站點.csv

In [ ]:
### 篩選大型站點
result = df.loc[
    df["大型站點"] == "是",
    [
        "BikesCapacity",
        "StationName.Zh_tw",
        "StationAddress.Zh_tw",
        "StationPosition.PositionLon",
        "StationPosition.PositionLat",
        "大型站點"
    ]
]


### 修改中文欄位名稱
result = result.rename(columns={
    "BikesCapacity": "可停放車位數",
    "StationName.Zh_tw": "站點名稱",
    "StationAddress.Zh_tw": "站點地址",
    "StationPosition.PositionLon": "經度",
    "StationPosition.PositionLat": "緯度",
    "大型站點": "大型站點"
})


### 顯示整理後資料
print("\n大型 YouBike 站點：")
result.head()

大型 YouBike 站點：
    可停放車位數                    站點名稱                站點地址         經度        緯度  \
19      99  YouBike2.0_捷運公館站(2號出口)       捷運公館站(2號出口)外側  121.53438  25.01491
20      87     YouBike2.0_第二學生活動中心     羅斯福路四段107號(西南側)  121.53661  25.01244
22      97     YouBike2.0_臺灣科技大學側門       基隆路四段73巷與基隆路口  121.53973  25.01295
24      99     YouBike2.0_臺灣科技大學後門  基隆路四段41巷68弄臺科帆船大樓旁  121.54165  25.01182
44      76    YouBike2.0_臺北市芳和實驗中學          臥龍街170號(前)  121.55013  25.01890

   大型站點
19    是
20    是
22    是
24    是
44    是

In [32]:
### 輸出 CSV
result.to_csv(
    "../pandas_output/大型YouBike站點.csv",
    index=False,
    encoding="utf-8-sig"
)

print("\n已產生：大型YouBike站點.csv")

已產生：大型YouBike站點.csv