前面學過 sum()、mean()、count()，這些方法可以直接計算整份資料。例如：


```
df["金額"].sum() # 計算所有交易的總金額
```

但實際分析時，我們通常不只想知道「全部花了多少錢？」，更常遇到的是「餐飲花多少？交通花多少？娛樂又花多少？」



groupby() 的概念其實很生活化。假設老師要計算每組學生的平均成績，可以先按照「組別」把學生分桌，再分別計算每桌的平均分數。

用班級生活比喻：`groupby`先依組別把同學分桌，再計算每桌人數或平均成績。

In [1]:
import pandas as pd


### 建立生活消費資料
data = {
    "交易編號": [
        "T001", "T002", "T003", "T004",
        "T005", "T006", "T007", "T008",
        "T009", "T010"
    ],
    "類別": [
        "餐飲", "交通", "餐飲", "娛樂",
        "交通", "餐飲", "娛樂", "交通",
        "餐飲", "娛樂"
    ],
    "付款方式": [
        "現金", "悠遊卡", "信用卡", "信用卡",
        "悠遊卡", "現金", "信用卡", "悠遊卡",
        "信用卡", "現金"
    ],
    "金額": [
        120, 50, 280, 450,
        35, 90, 600, 60,
        200, 300
    ]
}

df = pd.DataFrame(data)
df

   交易編號  類別 付款方式   金額
0  T001  餐飲   現金  120
1  T002  交通  悠遊卡   50
2  T003  餐飲  信用卡  280
3  T004  娛樂  信用卡  450
4  T005  交通  悠遊卡   35
5  T006  餐飲   現金   90
6  T007  娛樂  信用卡  600
7  T008  交通  悠遊卡   60
8  T009  餐飲  信用卡  200
9  T010  娛樂   現金  300

### sum()：每組總和

In [5]:
### 計算各類別總金額
category_total = df.groupby("類別")["金額"].sum() # 按照「類別」將資料分組，再把每個類別的「金額」加總起來。
category_total

類別
交通     145
娛樂    1350
餐飲     690
Name: 金額, dtype: int64

### mean()：每組平均

In [6]:
import pandas as pd

### 建立生活消費資料
data = {
    "交易編號": [
        "T001", "T002", "T003", "T004",
        "T005", "T006", "T007", "T008",
        "T009", "T010"
    ],
    "類別": [
        "餐飲", "交通", "餐飲", "娛樂",
        "交通", "餐飲", "娛樂", "交通",
        "餐飲", "娛樂"
    ],
    "付款方式": [
        "現金", "悠遊卡", "信用卡", "信用卡",
        "悠遊卡", "現金", "信用卡", "悠遊卡",
        "信用卡", "現金"
    ],
    "金額": [
        120, 50, 280, 450,
        35, 90, 600, 60,
        200, 300
    ]
}

df = pd.DataFrame(data)

### 計算各類別平均消費
result = df.groupby("類別")["金額"].mean()
result

類別
交通     48.333333
娛樂    450.000000
餐飲    172.500000
Name: 金額, dtype: float64

### max()：每組最大值

In [ ]:
import pandas as pd


### 建立生活消費資料
data = {
    "交易編號": [
        "T001", "T002", "T003", "T004",
        "T005", "T006", "T007", "T008",
        "T009", "T010"
    ],
    "類別": [
        "餐飲", "交通", "餐飲", "娛樂",
        "交通", "餐飲", "娛樂", "交通",
        "餐飲", "娛樂"
    ],
    "付款方式": [
        "現金", "悠遊卡", "信用卡", "信用卡",
        "悠遊卡", "現金", "信用卡", "悠遊卡",
        "信用卡", "現金"
    ],
    "金額": [
        120, 50, 280, 450,
        35, 90, 600, 60,
        200, 300
    ]
}

df = pd.DataFrame(data)

### 找出各類別最高單筆消費
result = df.groupby("類別")["金額"].max()
result

### min()：每組最小值

In [ ]:
import pandas as pd


### 建立生活消費資料
data = {
    "交易編號": [
        "T001", "T002", "T003", "T004",
        "T005", "T006", "T007", "T008",
        "T009", "T010"
    ],
    "類別": [
        "餐飲", "交通", "餐飲", "娛樂",
        "交通", "餐飲", "娛樂", "交通",
        "餐飲", "娛樂"
    ],
    "付款方式": [
        "現金", "悠遊卡", "信用卡", "信用卡",
        "悠遊卡", "現金", "信用卡", "悠遊卡",
        "信用卡", "現金"
    ],
    "金額": [
        120, 50, 280, 450,
        35, 90, 600, 60,
        200, 300
    ]
}

df = pd.DataFrame(data)

### 找出各類別最低單筆消費
result = df.groupby("類別")["金額"].min()
result

### size()：每組有幾筆資料

size()計算「每組有幾列」，會計算缺失值。

In [ ]:
import pandas as pd


### 建立生活消費資料
data = {
    "交易編號": [
        "T001", "T002", "T003", "T004",
        "T005", "T006", "T007", "T008",
        "T009", "T010"
    ],
    "類別": [
        "餐飲", "交通", "餐飲", "娛樂",
        "交通", "餐飲", "娛樂", "交通",
        "餐飲", "娛樂"
    ],
    "付款方式": [
        "現金", "悠遊卡", "信用卡", "信用卡",
        "悠遊卡", "現金", "信用卡", "悠遊卡",
        "信用卡", "現金"
    ],
    "金額": [
        120, 50, 280, 450,
        35, 90, 600, 60,
        200, 300
    ]
}

df = pd.DataFrame(data)

### 計算各類別交易筆數
result = df.groupby("類別").size()
result

### count()：計算非缺失值數量

count()計算「指定欄位有幾個非缺失值」，不會計算缺失值。

In [ ]:
import pandas as pd


### 建立生活消費資料
data = {
    "交易編號": [
        "T001", "T002", "T003", "T004",
        "T005", "T006", "T007", "T008",
        "T009", "T010"
    ],
    "類別": [
        "餐飲", "交通", "餐飲", "娛樂",
        "交通", "餐飲", "娛樂", "交通",
        "餐飲", "娛樂"
    ],
    "付款方式": [
        "現金", "悠遊卡", "信用卡", "信用卡",
        "悠遊卡", "現金", "信用卡", "悠遊卡",
        "信用卡", "現金"
    ],
    "金額": [
        120, 50, 280, 450,
        35, 90, 600, 60,
        200, 300
    ]
}

df = pd.DataFrame(data)

### 計算每組實際列數
print(df.groupby("類別").size())

### 計算金額欄位的非缺失值數量
print(df.groupby("類別")["金額"].count())

### agg()：Aggregate(聚合)的縮寫


```py
### 一次計算多項統計資料
summary = df.groupby("類別")["金額"].agg([
    "count",
    "sum",
    "mean",
    "max",
    "min"
])

print(summary)
```

In [ ]:
### 一次計算多個統計結果
import pandas as pd

### 建立生活消費資料
data = {
    "交易編號": [
        "T001", "T002", "T003", "T004",
        "T005", "T006", "T007", "T008",
        "T009", "T010"
    ],
    "類別": [
        "餐飲", "交通", "餐飲", "娛樂",
        "交通", "餐飲", "娛樂", "交通",
        "餐飲", "娛樂"
    ],
    "付款方式": [
        "現金", "悠遊卡", "信用卡", "信用卡",
        "悠遊卡", "現金", "信用卡", "悠遊卡",
        "信用卡", "現金"
    ],
    "金額": [
        120, 50, 280, 450,
        35, 90, 600, 60,
        200, 300
    ]
}

df = pd.DataFrame(data)

### 一次計算多項統計資料
summary = df.groupby("類別")["金額"].agg([
    "count",
    "sum",
    "mean",
    "max",
    "min"
])

summary

In [ ]:
### 自己命名統計欄位

import pandas as pd

### 建立生活消費資料
data = {
    "交易編號": [
        "T001", "T002", "T003", "T004",
        "T005", "T006", "T007", "T008",
        "T009", "T010"
    ],
    "類別": [
        "餐飲", "交通", "餐飲", "娛樂",
        "交通", "餐飲", "娛樂", "交通",
        "餐飲", "娛樂"
    ],
    "付款方式": [
        "現金", "悠遊卡", "信用卡", "信用卡",
        "悠遊卡", "現金", "信用卡", "悠遊卡",
        "信用卡", "現金"
    ],
    "金額": [
        120, 50, 280, 450,
        35, 90, 600, 60,
        200, 300
    ]
}

df = pd.DataFrame(data)

### 分組並建立統計摘要
summary = (
    df.groupby(
        "類別",
        as_index=False
    )
    .agg(
        交易筆數=("交易編號", "count"),
        總金額=("金額", "sum"),
        平均金額=("金額", "mean"),
        最高金額=("金額", "max"),
        最低金額=("金額", "min")
    )
)

summary

### as_index=False：類別也視為一列資料

In [ ]:
### 這樣寫：
import pandas as pd

### 建立生活消費資料
data = {
    "交易編號": [
        "T001", "T002", "T003", "T004",
        "T005", "T006", "T007", "T008",
        "T009", "T010"
    ],
    "類別": [
        "餐飲", "交通", "餐飲", "娛樂",
        "交通", "餐飲", "娛樂", "交通",
        "餐飲", "娛樂"
    ],
    "付款方式": [
        "現金", "悠遊卡", "信用卡", "信用卡",
        "悠遊卡", "現金", "信用卡", "悠遊卡",
        "信用卡", "現金"
    ],
    "金額": [
        120, 50, 280, 450,
        35, 90, 600, 60,
        200, 300
    ]
}

df = pd.DataFrame(data)
summary = df.groupby("類別")["金額"].sum()

summary

類別
交通     145
娛樂    1350
餐飲     690
Name: 金額, dtype: int64

In [ ]:
### 但很多時候我們希望「類別」繼續是一個普通欄位。這時可以：
import pandas as pd

### 建立生活消費資料
data = {
    "交易編號": [
        "T001", "T002", "T003", "T004",
        "T005", "T006", "T007", "T008",
        "T009", "T010"
    ],
    "類別": [
        "餐飲", "交通", "餐飲", "娛樂",
        "交通", "餐飲", "娛樂", "交通",
        "餐飲", "娛樂"
    ],
    "付款方式": [
        "現金", "悠遊卡", "信用卡", "信用卡",
        "悠遊卡", "現金", "信用卡", "悠遊卡",
        "信用卡", "現金"
    ],
    "金額": [
        120, 50, 280, 450,
        35, 90, 600, 60,
        200, 300
    ]
}

df = pd.DataFrame(data)
summary = df.groupby("類別", as_index=False)["金額"].sum()

summary

   類別    金額
0  交通   145
1  娛樂  1350
2  餐飲   690