### sort_values()：按照欄位內容排序

- by：按照哪個欄位排序
- ascending=True：由小到大
- ascending=False：由大到小

In [1]:
import pandas as pd

### 建立學生成績資料
data = {
    "姓名": ["小明", "小美", "小華", "小安", "小傑"],
    "國文": [78, 92, 85, 67, 88],
    "數學": [90, 76, 88, 95, 82]
}

df = pd.DataFrame(data)

### 按照數學成績由小到大排序
result = df.sort_values(
    by="數學",
    ascending=True
)

print("\n數學成績由小到大：")
print(result)


### 按照數學成績由大到小排序
result = df.sort_values(
    by="數學",
    ascending=False
)

print("\n數學成績由大到小：")
print(result)

數學成績由小到大：
   姓名  國文  數學
1  小美  92  76
4  小傑  88  82
2  小華  85  88
0  小明  78  90
3  小安  67  95

數學成績由大到小：
   姓名  國文  數學
3  小安  67  95
0  小明  78  90
2  小華  85  88
4  小傑  88  82
1  小美  92  76

### 多欄位排序

實際資料分析很少只有一個排序規則。例如先按照「狀態」排序，如果狀態相同，再按照「實付金額」由高到低排序。

In [ ]:
import pandas as pd

### 建立訂單資料
data = {
    "訂單編號": ["A001", "A002", "A003", "A004", "A005", "A006"],
    "餐點金額": [180, 320, 250, 450, 150, 380],
    "外送費": [30, 0, 40, 0, 30, 20],
    "折扣": [20, 50, 0, 80, 10, 30],
    "狀態": ["已完成", "已完成", "已取消", "已完成", "已取消", "已完成"]
}

df = pd.DataFrame(data)

### 計算實付金額
df["實付金額"] = (df["餐點金額"] + df["外送費"] - df["折扣"] )

### 使用兩個欄位排序
result = df.sort_values(
    by=["狀態", "實付金額"],
    ascending=[True, False]
)
result

   訂單編號  餐點金額  外送費  折扣   狀態  實付金額
2  A003   250   40   0  已取消   290
4  A005   150   30  10  已取消   170
3  A004   450    0  80  已完成   370
5  A006   380   20  30  已完成   370
1  A002   320    0  50  已完成   270
0  A001   180   30  20  已完成   190

### nlargest()：找最大的前幾筆

In [3]:
# 實付金額最高的 3 筆訂單是哪幾筆？
import pandas as pd

### 建立訂單資料
data = {
    "訂單編號": ["A001", "A002", "A003", "A004", "A005", "A006"],
    "餐點金額": [180, 320, 250, 450, 150, 380],
    "外送費": [30, 0, 40, 0, 30, 20],
    "折扣": [20, 50, 0, 80, 10, 30],
    "狀態": ["已完成", "已完成", "已取消", "已完成", "已取消", "已完成"]
}

df = pd.DataFrame(data)

### 計算實付金額
df["實付金額"] = (df["餐點金額"] + df["外送費"] - df["折扣"] )

### 找出實付金額最高的 3 筆
top3 = df.nlargest(
    3,
    "實付金額"
)

top3

   訂單編號  餐點金額  外送費  折扣   狀態  實付金額
3  A004   450    0  80  已完成   370
5  A006   380   20  30  已完成   370
2  A003   250   40   0  已取消   290

### nsmallest()：找最小的前幾筆

In [4]:
# 實付金額最高的 3 筆訂單是哪幾筆？
import pandas as pd

### 建立訂單資料
data = {
    "訂單編號": ["A001", "A002", "A003", "A004", "A005", "A006"],
    "餐點金額": [180, 320, 250, 450, 150, 380],
    "外送費": [30, 0, 40, 0, 30, 20],
    "折扣": [20, 50, 0, 80, 10, 30],
    "狀態": ["已完成", "已完成", "已取消", "已完成", "已取消", "已完成"]
}

df = pd.DataFrame(data)

### 計算實付金額
df["實付金額"] = (df["餐點金額"] + df["外送費"] - df["折扣"] )

### 找出實付金額最高的 3 筆
top3 = df.nsmallest(
    3,
    "實付金額"
)

top3

   訂單編號  餐點金額  外送費  折扣   狀態  實付金額
4  A005   150   30  10  已取消   170
0  A001   180   30  20  已完成   190
1  A002   320    0  50  已完成   270