Pandas 最大優勢之一是向量化：對整欄描述規則，不必手寫逐列迴圈。

### 新增欄位

In [1]:
import pandas as pd

### 建立訂單資料
data = {
    "訂單編號": ["A001", "A002", "A003", "A004"],
    "餐點金額": [180, 320, 250, 450],
    "外送費": [30, 0, 40, 0],
    "折扣": [20, 50, 0, 80],
    "狀態": ["完成", "完成", "取消", "完成"]
}

df = pd.DataFrame(data)
### 新增固定內容的欄位
df["平台"] = "FoodGo"

df

   訂單編號  餐點金額  外送費  折扣  狀態      平台
0  A001   180   30  20  完成  FoodGo
1  A002   320    0  50  完成  FoodGo
2  A003   250   40   0  取消  FoodGo
3  A004   450    0  80  完成  FoodGo

### 修改原本的欄位

In [4]:
import pandas as pd


### 建立訂單資料
data = {
    "訂單編號": ["A001", "A002", "A003", "A004"],
    "餐點金額": [180, 320, 250, 450],
    "外送費": [30, 0, 40, 0],
    "折扣": [20, 50, 0, 80],
    "狀態": ["完成", "完成", "取消", "完成"]
}

df = pd.DataFrame(data)

### 修改原本的餐點金額
df["餐點金額"] = df["餐點金額"] + 10
df

   訂單編號  餐點金額  外送費  折扣  狀態
0  A001   190   30  20  完成
1  A002   330    0  50  完成
2  A003   260   40   0  取消
3  A004   460    0  80  完成

### 使用原本的欄位計算新欄位

In [2]:
import pandas as pd

### 建立訂單資料
data = {
    "訂單編號": ["A001", "A002", "A003", "A004"],
    "餐點金額": [180, 320, 250, 450],
    "外送費": [30, 0, 40, 0],
    "折扣": [20, 50, 0, 80],
    "狀態": ["完成", "完成", "取消", "完成"]
}

df = pd.DataFrame(data)
### 計算每筆訂單的實付金額
df["實付金額"] = (df["餐點金額"] + df["外送費"] - df["折扣"])
df

   訂單編號  餐點金額  外送費  折扣  狀態  實付金額
0  A001   180   30  20  完成   190
1  A002   320    0  50  完成   270
2  A003   250   40   0  取消   290
3  A004   450    0  80  完成   370

### 使用條件建立True/False欄位

In [3]:
import pandas as pd

### 建立訂單資料
data = {
    "訂單編號": ["A001", "A002", "A003", "A004"],
    "餐點金額": [180, 320, 250, 450],
    "外送費": [30, 0, 40, 0],
    "折扣": [20, 50, 0, 80],
    "狀態": ["完成", "完成", "取消", "完成"]
}

df = pd.DataFrame(data)
### 計算每筆訂單的實付金額
df["實付金額"] = (df["餐點金額"] + df["外送費"] - df["折扣"])
### 判斷是否為大額訂單
df["大額訂單"] = df["實付金額"] >= 300

df[["訂單編號", "實付金額", "大額訂單"]]

   訂單編號  實付金額   大額訂單
0  A001   190  False
1  A002   270  False
2  A003   290  False
3  A004   370   True

### replace()：替換指定內容

資料清洗時很常遇到同一件事情有不同寫法。
例如：
```
完成
取消
處理中
```
但系統希望統一成：
```
已完成
已取消
處理中
```

In [5]:

import pandas as pd

### 建立訂單資料
data = {
    "訂單編號": ["A001", "A002", "A003", "A004"],
    "餐點金額": [180, 320, 250, 450],
    "外送費": [30, 0, 40, 0],
    "折扣": [20, 50, 0, 80],
    "狀態": ["完成", "完成", "取消", "完成"]
}

df = pd.DataFrame(data)

### 替換指定內容
df["狀態"] = df["狀態"].replace({
    "完成": "已完成",
    "取消": "已取消"
})
df

   訂單編號  餐點金額  外送費  折扣   狀態
0  A001   180   30  20  已完成
1  A002   320    0  50  已完成
2  A003   250   40   0  已取消
3  A004   450    0  80  已完成

### map()：按照對照表轉換資料

In [ ]:
import pandas as pd

### 建立訂單資料
data = {
    "訂單編號": ["A001", "A002", "A003", "A004"],
    "餐點金額": [180, 320, 250, 450],
    "外送費": [30, 0, 40, 0],
    "折扣": [20, 50, 0, 80],
    "狀態": ["完成", "完成", "取消", "完成"],
    "星期代碼": [0, 1, 2, 3]
}

df = pd.DataFrame(data)

### 建立星期對照表
weekday_map = {
    0: "星期一",
    1: "星期二",
    2: "星期三",
    3: "星期四",
    4: "星期五",
    5: "星期六",
    6: "星期日"
}


### 使用 map 將星期代碼轉換成中文
df["星期"] = df["星期代碼"].map(
    weekday_map
) # 根據 weekday_map 的對照規則，將 0、1、2、3 轉換成對應的星期文字
df

   訂單編號  餐點金額  外送費  折扣  狀態  星期代碼   星期
0  A001   180   30  20  完成     0  星期一
1  A002   320    0  50  完成     1  星期二
2  A003   250   40   0  取消     2  星期三
3  A004   450    0  80  完成     3  星期四