### 建立資料

In [2]:
import pandas as pd

df = pd.DataFrame({
    "訂單編號": ["A001", "A002", "A003", "A004", "A005"],
    "餐點": ["牛肉麵", "雞腿飯", "火鍋", "水餃", "咖哩飯"],
    "餐點金額": [180, 120, 350, 90, 250],
    "狀態": ["完成", "完成", "未完成", "取消", "完成"],
    "付款方式": ["現金", "信用卡", "信用卡", "現金", "LINE Pay"]
})

df

   訂單編號   餐點  餐點金額   狀態      付款方式
0  A001  牛肉麵   180   完成        現金
1  A002  雞腿飯   120   完成       信用卡
2  A003   火鍋   350  未完成       信用卡
3  A004   水餃    90   取消        現金
4  A005  咖哩飯   250   完成  LINE Pay

### 選欄位：「我只想看哪些資料？」

In [7]:
result_Series = df["餐點金額"] 
result_Series

0    180
1    120
2    350
3     90
4    250
Name: 餐點金額, dtype: int64

In [6]:
result_DataFrame = df[["訂單編號", "餐點金額"]]
result_DataFrame

   訂單編號  餐點金額
0  A001   180
1  A002   120
2  A003   350
3  A004    90
4  A005   250

### loc 與 iloc：「我要指定哪些位置的資料？」

- df.loc[我要哪些列, 我要哪些欄]`：看標籤、名稱、條件
    - `
- iloc：看第幾列、第幾欄

In [9]:
result = df.loc[df["餐點金額"] >= 250, ["訂單編號", "餐點金額"]]
result

   訂單編號  餐點金額
2  A003   350
4  A005   250

In [10]:
result = df.iloc[:3, :2] # 我要前 3 筆資料，而且只看前 2 欄。
result

   訂單編號   餐點
0  A001  牛肉麵
1  A002  雞腿飯
2  A003   火鍋

### 布林篩選：「哪些資料符合我的條件？」

In [11]:
# 情境：餐廳想找出所有「已完成，而且餐點金額 >= 150」的訂單。
# 可以先拆成兩個條件：
# 1. df["狀態"] == "完成"
# 2. df["餐點金額"] >= 150
# 3. 再把兩個條件使用 & 結合

result = df[
    (df["狀態"] == "完成") &
    (df["餐點金額"] >= 150)
]

result

   訂單編號   餐點  餐點金額  狀態      付款方式
0  A001  牛肉麵   180  完成        現金
4  A005  咖哩飯   250  完成  LINE Pay