### 建立範例資料

In [ ]:
import pandas as pd


### 建立交易資料
data = {
    "交易編號": ["T001","T002","T003","T003","T004","T005","T005"],
    "商品": ["珍珠奶茶","珍珠奶茶","雞排","雞排","紅茶","蛋餅","蛋餅"],
    "金額": [65,65,90,90,40,55,55]
}

df = pd.DataFrame(data)

### 顯示原始資料
print("原始資料：")
df

原始資料：

   交易編號    商品   金額
0  T001  珍珠奶茶   65
1  T002  珍珠奶茶   65
2  T003    雞排   90
3  T003    雞排   90
4  T004    紅茶   40
5  T005    蛋餅  555
6  T005    蛋餅   55

### duplicated()：檢查整列是否重複

In [5]:
df.duplicated()
# False 代表重複的第二項

0    False
1    False
2    False
3     True
4    False
5    False
6    False
dtype: bool

In [6]:
### subset：指定用哪個欄位判斷重複：真實資料不一定整列完全相同。
df.duplicated(subset=["交易編號"])

0    False
1    False
2    False
3     True
4    False
5    False
6     True
dtype: bool

In [7]:
### keep=False：把所有重複資料都找出來
# 如果想把重複交易的第一次和後續出現全部標記出來，可以使用
df.duplicated(
    subset=["交易編號"],
    keep=False
)

0    False
1    False
2     True
3     True
4    False
5     True
6     True
dtype: bool

### drop_duplicates()：刪除重複資料

In [7]:
# 如果我們認為「交易編號」應該唯一，可以指定：
df = df.drop_duplicates(
    subset=["交易編號"], # 如果交易編號重複，只保留第一次出現的資料。
    keep="first"
    # keep有三種
    # first：保留第一筆
    # last：保留最後一筆
    # False：重複的全部刪除
)
df

   交易編號    商品  金額
0  T001  珍珠奶茶  65
1  T002  珍珠奶茶  65
2  T003    雞排  90
4  T004    紅茶  40
5  T005    蛋餅  55

## Problem. 重複值實作練習

In [8]:
import pandas as pd


### 建立訂單資料
data = {
    "訂單編號": [
        "A001", "A002", "A003", "A003",
        "A004", "A005", "A005", "A006"
    ],
    "商品": [
        "紅茶", "珍珠奶茶", "雞排", "雞排",
        "綠茶", "蛋餅", "蛋餅", "咖啡"
    ],
    "金額": [
        30, 65, 90, 90,
        35, 55, 55, 80
    ]
}

df = pd.DataFrame(data)
df

   訂單編號    商品  金額
0  A001    紅茶  30
1  A002  珍珠奶茶  65
2  A003    雞排  90
3  A003    雞排  90
4  A004    綠茶  35
5  A005    蛋餅  55
6  A005    蛋餅  55
7  A006    咖啡  80

### Problem. 哪些資料整列重複？

- 使用 duplicated() 檢查資料。
- 顯示每一列是否為重複資料。
- 觀察哪些資料得到 True。

### Problem. 只用訂單編號判斷重複 

請只根據「訂單編號」檢查重複資料。

預期 A003 與 A005 都存在重複情況。

### Problem. 把所有重複訂單都找出來

主管想檢查完整的異常資料，所以不能只看到第二次出現的資料。

例如：
```
A003
A003
```
兩筆都要標記為 True。

### Problem. 刪除重複訂單，保留第一筆 
請完成：
- 根據「訂單編號」判斷重複。
- 發生重複時保留第一筆。
- 刪除後面重複出現的資料。
- 將整理結果重新存回 df。

### Problem. 重複的全部不要

「只要訂單編號重複，我就無法確定哪一筆才正確，所以整組都先排除。」

例如：
```
A003
A003
```
不是留下其中一筆，而是兩筆全部刪除。

請使用 drop_duplicates() 完成資料清理。要求：

- 根據「訂單編號」判斷。
- 重複資料全部刪除。
- A003 不應留下任何資料。
- A005 也不應留下任何資料。