### 建立範例資料

In [1]:
import pandas as pd


### 建立交易資料
data = {
    "交易編號": [
        "T001",
        "T002",
        "T003",
        "T003",
        "T004",
        "T005",
        "T005"
    ],
    "商品": [
        "珍珠奶茶",
        "珍珠奶茶",
        "雞排",
        "雞排",
        "紅茶",
        "蛋餅",
        "蛋餅"
    ],
    "金額": [
        65,
        65,
        90,
        90,
        40,
        55,
        55
    ]
}

df = pd.DataFrame(data)


### 顯示原始資料
print("原始資料：")
df

原始資料：

   交易編號    商品  金額
0  T001  珍珠奶茶  65
1  T002  珍珠奶茶  65
2  T003    雞排  90
3  T003    雞排  90
4  T004    紅茶  40
5  T005    蛋餅  55
6  T005    蛋餅  55

### duplicated()：檢查整列是否重複

In [2]:
df.duplicated()

0    False
1    False
2    False
3     True
4    False
5    False
6     True
dtype: bool

### subset：指定用哪個欄位判斷重複

真實資料不一定整列完全相同。

In [4]:
df.duplicated(
    subset=["交易編號"]
)

0    False
1    False
2    False
3     True
4    False
5    False
6     True
dtype: bool

### keep=False：把所有重複資料都找出來

如果想把重複交易的第一次和後續出現全部標記出來，可以使用

In [5]:
df.duplicated(
    subset=["交易編號"],
    keep=False
)

0    False
1    False
2     True
3     True
4    False
5     True
6     True
dtype: bool

### drop_duplicates()：刪除重複資料

In [7]:
# 如果我們認為「交易編號」應該唯一，可以指定：
df = df.drop_duplicates(
    subset=["交易編號"], # 如果交易編號重複，只保留第一次出現的資料。
    keep="first"
    # keep有三種
    # first：保留第一筆
    # last：保留最後一筆
    # False：重複的全部刪除
)
df

   交易編號    商品  金額
0  T001  珍珠奶茶  65
1  T002  珍珠奶茶  65
2  T003    雞排  90
4  T004    紅茶  40
5  T005    蛋餅  55

### Problem

In [8]:
import pandas as pd


### 建立訂單資料
data = {
    "訂單編號": [
        "A001",
        "A002",
        "A003",
        "A003",
        "A004",
        "A005",
        "A006",
        "A006",
        "A007",
        "A008"
    ],
    "餐點": [
        "雞腿便當",
        "珍珠奶茶",
        "牛肉麵",
        "牛肉麵",
        "珍珠奶茶",
        "雞排",
        "鍋燒意麵",
        "鍋燒意麵",
        "雞排",
        "珍珠奶茶"
    ],
    "金額": [
        120,
        65,
        150,
        150,
        65,
        90,
        110,
        110,
        90,
        65
    ],
    "付款方式": [
        "現金",
        "信用卡",
        "Line Pay",
        "Line Pay",
        "信用卡",
        "現金",
        "信用卡",
        "信用卡",
        "現金",
        "信用卡"
    ]
}

df = pd.DataFrame(data)
df

   訂單編號    餐點   金額      付款方式
0  A001  雞腿便當  120        現金
1  A002  珍珠奶茶   65       信用卡
2  A003   牛肉麵  150  Line Pay
3  A003   牛肉麵  150  Line Pay
4  A004  珍珠奶茶   65       信用卡
5  A005    雞排   90        現金
6  A006  鍋燒意麵  110       信用卡
7  A006  鍋燒意麵  110       信用卡
8  A007    雞排   90        現金
9  A008  珍珠奶茶   65       信用卡

### Problem. 
- 請列出重複資料

In [9]:
df.duplicated()

0    False
1    False
2    False
3     True
4    False
5    False
6    False
7     True
8    False
9    False
dtype: bool

### Problem. 
只根據「訂單編號」判斷資料是否重複

In [10]:
df.duplicated(
    subset=["訂單編號"]
)
df

   訂單編號    餐點   金額      付款方式
0  A001  雞腿便當  120        現金
1  A002  珍珠奶茶   65       信用卡
2  A003   牛肉麵  150  Line Pay
3  A003   牛肉麵  150  Line Pay
4  A004  珍珠奶茶   65       信用卡
5  A005    雞排   90        現金
6  A006  鍋燒意麵  110       信用卡
7  A006  鍋燒意麵  110       信用卡
8  A007    雞排   90        現金
9  A008  珍珠奶茶   65       信用卡

### Problem. 
現在希望把重複訂單的「第一次和後續資料」全部找出來。

In [13]:
df.duplicated(
    subset=["訂單編號"],
    keep=False
)

0    False
1    False
2     True
3     True
4    False
5    False
6     True
7     True
8    False
9    False
dtype: bool