# 排序

## sort_values()：按照欄位內容排序

- by：按照哪個欄位排序
- ascending=True：由小到大
- ascending=False：由大到小

In [ ]:
import pandas as pd

## 建立學生成績資料
data = {
    "姓名": ["小明", "小美", "小華", "小安", "小傑"],
    "國文": [78, 92, 85, 67, 88],
    "數學": [90, 76, 88, 95, 82]
}

df = pd.DataFrame(data)
df

   姓名  國文  數學
0  小明  78  90
1  小美  92  76
2  小華  85  88
3  小安  67  95
4  小傑  88  82

In [ ]:
## 按照數學成績由小到大排序
result = df.sort_values(
    by="數學",
    ascending=True
)

print("\n數學成績由小到大：")
result

數學成績由小到大：

   姓名  國文  數學
1  小美  92  76
4  小傑  88  82
2  小華  85  88
0  小明  78  90
3  小安  67  95

In [ ]:

## 按照數學成績由大到小排序
result = df.sort_values(
    by="數學",
    ascending=False
)

print("\n數學成績由大到小：")
result

數學成績由大到小：

   姓名  國文  數學
3  小安  67  95
0  小明  78  90
2  小華  85  88
4  小傑  88  82
1  小美  92  76

## 多欄位排序

實際資料分析很少只有一個排序規則。例如先按照「狀態」排序，如果狀態相同，再按照「實付金額」由高到低排序。

In [ ]:
import pandas as pd

## 建立訂單資料
data = {
    "訂單編號": ["A001", "A002", "A003", "A004", "A005", "A006"],
    "餐點金額": [180, 320, 250, 450, 150, 380],
    "外送費": [30, 0, 40, 0, 30, 20],
    "折扣": [20, 50, 0, 80, 10, 30],
    "狀態": ["已完成", "已完成", "已取消", "已完成", "已取消", "已完成"]
}

df = pd.DataFrame(data)

## 計算實付金額
df["實付金額"] = (df["餐點金額"] + df["外送費"] - df["折扣"] )

## 使用兩個欄位排序
result = df.sort_values(
    by=["狀態", "實付金額"],
    ascending=[True, False]
)
result

   訂單編號  餐點金額  外送費  折扣   狀態  實付金額
2  A003   250   40   0  已取消   290
4  A005   150   30  10  已取消   170
3  A004   450    0  80  已完成   370
5  A006   380   20  30  已完成   370
1  A002   320    0  50  已完成   270
0  A001   180   30  20  已完成   190

## nlargest()：找最大的前幾筆

In [ ]:
# 實付金額最高的 3 筆訂單是哪幾筆？
import pandas as pd

## 建立訂單資料
data = {
    "訂單編號": ["A001", "A002", "A003", "A004", "A005", "A006"],
    "餐點金額": [180, 320, 250, 450, 150, 380],
    "外送費": [30, 0, 40, 0, 30, 20],
    "折扣": [20, 50, 0, 80, 10, 30],
    "狀態": ["已完成", "已完成", "已取消", "已完成", "已取消", "已完成"]
}

df = pd.DataFrame(data)

## 計算實付金額
df["實付金額"] = (df["餐點金額"] + df["外送費"] - df["折扣"] )

## 找出實付金額最高的 3 筆
df.nlargest(3, "實付金額")

   訂單編號  餐點金額  外送費  折扣   狀態  實付金額
3  A004   450    0  80  已完成   370
5  A006   380   20  30  已完成   370
2  A003   250   40   0  已取消   290

## nsmallest()：找最小的前幾筆

In [ ]:
# 實付金額最高的 3 筆訂單是哪幾筆？
import pandas as pd

## 建立訂單資料
data = {
    "訂單編號": ["A001", "A002", "A003", "A004", "A005", "A006"],
    "餐點金額": [180, 320, 250, 450, 150, 380],
    "外送費": [30, 0, 40, 0, 30, 20],
    "折扣": [20, 50, 0, 80, 10, 30],
    "狀態": ["已完成", "已完成", "已取消", "已完成", "已取消", "已完成"]
}

df = pd.DataFrame(data)

## 計算實付金額
df["實付金額"] = (df["餐點金額"] + df["外送費"] - df["折扣"] )

## 找出實付金額最高的 3 筆
df.nsmallest(3, "實付金額")

   訂單編號  餐點金額  外送費  折扣   狀態  實付金額
4  A005   150   30  10  已取消   170
0  A001   180   30  20  已完成   190
1  A002   320    0  50  已完成   270

## 練習：電商商品銷售排行

電商平台想整理本月商品的銷售狀況，請依照不同需求進行排序。

In [ ]:
import pandas as pd


## 建立商品銷售資料
data = {
    "商品": ["藍牙耳機", "機械鍵盤", "滑鼠", "行動電源", "手機支架", "充電線", "筆電架"],
    "類別": ["3C配件", "電腦周邊", "電腦周邊", "3C配件", "3C配件", "3C配件", "電腦周邊"],
    "價格": [1290, 2490, 890, 1590, 450, 390, 1200],
    "銷售數量": [85, 42, 120, 68, 150, 210, 55]
}

df = pd.DataFrame(data)
df

請完成以下任務：

1. 按照 `"價格"` **由小到大**排序。
2. 按照 `"價格"` **由大到小**排序。
3. 按照 `"銷售數量"` **由大到小**排序。
4. 先按照 `"類別"` 由小到大排序，如果類別相同，再按照 `"價格"` **由高到低**排序。
5. 使用 `nlargest()` 找出**價格最高的 3 項商品**。
6. 使用 `nsmallest()` 找出**價格最低的 3 項商品**。
7. 使用 `nlargest()` 找出**銷售數量最高的 2 項商品**。

## 練習：租屋物件排序

租屋平台整理了一批房屋資料。不同租客在意的條件不同，請依照指定需求進行排序。

In [ ]:
import pandas as pd


## 建立租屋資料
data = {
    "物件編號": ["H001", "H002", "H003", "H004", "H005", "H006", "H007", "H008"],
    "區域": ["東區", "北區", "東區", "南區", "北區", "東區", "南區", "北區"],
    "房型": ["套房", "兩房", "套房", "三房", "套房", "兩房", "兩房", "三房"],
    "月租": [8500, 15000, 7200, 22000, 9000, 16800, 13500, 24000],
    "室內坪數": [8, 18, 7, 30, 9, 20, 16, 32]
}

df = pd.DataFrame(data)
df

請完成以下任務：

1. 按照 `"月租"` **由低到高**排序。
2. 按照 `"室內坪數"` **由大到小**排序。
3. 先按照 `"區域"` 由小到大排序，如果區域相同，再按照 `"月租"` **由低到高**排序。
4. 先按照 `"房型"` 由小到大排序，如果房型相同，再按照 `"室內坪數"` **由大到小**排序。
5. 使用 `nsmallest()` 找出**月租最低的 3 間房子**。
6. 使用 `nlargest()` 找出**室內坪數最大的 3 間房子**。
7. 小資族想優先找便宜的房子，請找出**月租最低的 2 間房子**。
8. 想找空間最大的房子，請找出**室內坪數最大的 2 間房子**。