# 缺失值
Pandas 常以 NaN、NaT 表示缺失值。

缺失不一定代表「資料錯了」，它可能來自很多情況，例如：

- 使用者忘記填寫
- 系統沒有成功取得資料
- 該欄位不適用
- 使用者拒絕提供
- 資料匯入時格式錯誤

所以看到缺失值時，不是立刻全部刪掉，而是先判斷這個欄位對分析有多重要。

```py
df.isna() # 檢查每個位置是否為缺失值
df.isna().sum() # 統計每個欄位有多少個缺失值
```

### 策略一：刪除缺失資料

有些欄位不能缺。

例如「交易編號」如果不存在，後續就很難辨認這筆交易，也可能無法和其他資料表進行 merge。這種情況可以直接刪除。

In [2]:
import pandas as pd


### 建立範例資料
data = {
    "交易編號": ["T001", "T002", None, "T004"],
    "類別": ["餐飲", "交通", "購物", "餐飲"],
    "金額": [120, 250, 300, None]
}

df = pd.DataFrame(data)

### dropna() 用來刪除含有缺失值的資料列。
df = df.dropna(
    subset=["交易編號"] # 指定「我要檢查哪些欄位」
) 

df

   交易編號  類別     金額
0  T001  餐飲  120.0
1  T002  交通  250.0
3  T004  餐飲    NaN

### 策略二：填補缺失值

有些資料雖然缺失，但不需要直接刪掉。

In [4]:
import pandas as pd


### 建立範例資料
data = {
    "交易編號": ["T001", "T002", "T003", "T004"],
    "類別": ["餐飲", None, "交通", None],
    "金額": [120, 250, None, 180]
}

df = pd.DataFrame(data)

### 填補缺失值
df["類別"] = df["類別"].fillna("未分類") # 將「類別」缺失的位置填成「未分類」
df

   交易編號   類別     金額
0  T001   餐飲  120.0
1  T002  未分類  250.0
2  T003   交通    NaN
3  T004  未分類  180.0

In [5]:
# 數值資料也可以填補。
# 例如有一筆「金額」缺失，就用金額中位數去補
median_amount = df["金額"].median() # 計算金額中位數

df["金額"] = df["金額"].fillna(median_amount) # 使用中位數填補缺失金額
df

   交易編號   類別     金額
0  T001   餐飲  120.0
1  T002  未分類  250.0
2  T003   交通  180.0
3  T004  未分類  180.0

### 策略三：保留缺失值，另外建立標記

有時候「缺失」本身就是資訊。

例如「金額沒有填」，可能代表：

- 系統取得資料失敗
- 使用者沒有提供
- 某種特殊交易沒有金額
- 資料串接發生問題

如果直接把缺失值填掉，這些資訊就消失了。這時可以建立一個新的欄位，記錄原本是否缺失。

In [6]:
import pandas as pd


### 建立範例資料
data = {
    "交易編號": ["T001", "T002", "T003", "T004"],
    "類別": ["餐飲", "交通", "購物", "餐飲"],
    "金額": [120, None, 300, None]
}

df = pd.DataFrame(data)

### 建立缺失標記欄位
df["金額是否缺失"] = df["金額"].isna()
df

   交易編號  類別     金額  金額是否缺失
0  T001  餐飲  120.0   False
1  T002  交通    NaN    True
2  T003  購物  300.0   False
3  T004  餐飲    NaN    True


### 練習：外送訂單缺失值處理

外送平台匯出了一份訂單資料，但部分資料沒有成功寫入。請先檢查缺失情況，再依照不同欄位的重要程度進行處理。

In [ ]:
import pandas as pd


### 建立資料
data = {
    "訂單編號": ["A001", "A002", None, "A004", "A005", "A006"],
    "餐點": ["雞腿便當", "牛肉麵", "鍋燒意麵", None, "水餃", "排骨飯"],
    "付款方式": ["現金", None, "信用卡", "LINE Pay", None, "現金"],
    "金額": [120, 150, 110, 180, None, None]
}

df = pd.DataFrame(data)
df


請完成以下任務：

1. 使用 `isna()` 檢查每個資料位置是否為缺失值。
2. 統計每個欄位分別有幾個缺失值。
3. `"訂單編號"` 是辨識訂單的重要資料。刪除 `"訂單編號"` 缺失的整筆資料，並將結果重新存回 `df`。
4. `"付款方式"` 缺失不代表整筆訂單無效，將缺失值填成 `"未知"`。
5. `"金額"` 有部分資料缺失，先計算目前 `"金額"` 的中位數，存入 `median_amount`。
6. 使用 `median_amount` 填補 `"金額"` 的缺失值。
7. `"餐點"` 缺失可能代表資料匯入異常，因此**不要刪除，也不要填補**。新增 `"餐點是否缺失"` 欄位，原本缺失為 `True`，否則為 `False`。
8. 顯示最後處理完成的 `df`。

### 練習：學生課程紀錄缺失值處理

老師整理學生的課程紀錄時，發現部分欄位沒有填寫。不同欄位缺失的處理方式不同，請依照要求整理資料。

In [ ]:
import pandas as pd


### 建立資料
data = {
    "學號": ["S001", "S002", "S003", None, "S005", "S006", "S007"],
    "姓名": ["小明", "小華", "小美", "阿哲", "小安", "小宇", "小杰"],
    "班級": ["A班", None, "B班", "A班", "B班", None, "A班"],
    "成績": [85, 72, None, 91, 68, None, 80],
    "作業狀態": ["已繳交", "已繳交", None, "已繳交", "未繳交", None, "已繳交"]
}

df = pd.DataFrame(data)
df

請完成以下任務：

1. 統計每個欄位的缺失值數量。
2. `"學號"` 是辨識學生的重要資料。只檢查 `"學號"` 欄位，學號缺失就刪除整筆資料。
3. `"班級"` 沒有填寫時仍然保留學生資料，將缺失值填成 `"未分班"`。
4. `"成績"` 缺失時不直接填 0。先計算現有成績的中位數，存入 `median_score`。
5. 使用 `median_score` 填補 `"成績"` 的缺失值。
6. `"作業狀態"` 缺失可能代表系統沒有成功取得繳交紀錄，因此**先不要填補**。
7. 新增 `"作業狀態是否缺失"` 欄位，原本 `"作業狀態"` 缺失為 `True`，否則為 `False`。
8. 再次使用 `isna().sum()`，確認經過處理後還有哪些欄位存在缺失值。
9. 顯示最後處理完成的 `df`。