# 重複值
## 建立範例資料

In [ ]:
import pandas as pd


### 建立交易資料
data = {
    "交易編號": ["T001","T002","T003","T003","T004","T005","T005"],
    "商品": ["珍珠奶茶","珍珠奶茶","雞排","雞排","紅茶","蛋餅","蛋餅"],
    "金額": [65,65,90,90,40,55,55]
}

df = pd.DataFrame(data)

### 顯示原始資料
print("原始資料：")
df

原始資料：

   交易編號    商品   金額
0  T001  珍珠奶茶   65
1  T002  珍珠奶茶   65
2  T003    雞排   90
3  T003    雞排   90
4  T004    紅茶   40
5  T005    蛋餅  555
6  T005    蛋餅   55

## duplicated()：檢查整列是否重複

In [5]:
df.duplicated()
# False 代表重複的第二項

0    False
1    False
2    False
3     True
4    False
5    False
6    False
dtype: bool

In [6]:
### subset：指定用哪個欄位判斷重複：真實資料不一定整列完全相同。
df.duplicated(subset=["交易編號"])

0    False
1    False
2    False
3     True
4    False
5    False
6     True
dtype: bool

In [7]:
### keep=False：把所有重複資料都找出來
# 如果想把重複交易的第一次和後續出現全部標記出來，可以使用
df.duplicated(
    subset=["交易編號"],
    keep=False
)

0    False
1    False
2     True
3     True
4    False
5     True
6     True
dtype: bool

## drop_duplicates()：刪除重複資料

In [7]:
# 如果我們認為「交易編號」應該唯一，可以指定：
df = df.drop_duplicates(
    subset=["交易編號"], # 如果交易編號重複，只保留第一次出現的資料。
    keep="first"
    # keep有三種
    # first：保留第一筆
    # last：保留最後一筆
    # False：重複的全部刪除
)
df

   交易編號    商品  金額
0  T001  珍珠奶茶  65
1  T002  珍珠奶茶  65
2  T003    雞排  90
4  T004    紅茶  40
5  T005    蛋餅  55

## 練習：會員消費紀錄重複資料

健身房匯出會員消費紀錄時，系統可能重複寫入同一筆交易。請檢查並處理重複資料。

In [ ]:
import pandas as pd


### 建立會員消費資料
data = {
    "交易編號": [
        "M001", "M002", "M003", "M003",
        "M004", "M005", "M005", "M006"
    ],
    "會員": [
        "小明", "小華", "小美", "小美",
        "阿哲", "小安", "小安", "小宇"
    ],
    "消費金額": [
        120, 250, 180, 180,
        300, 150, 150, 220
    ]
}

df = pd.DataFrame(data)
df

請完成以下任務：

1. 使用 `duplicated()` 檢查是否有**整列完全相同**的資料。
2. 只根據 `"交易編號"` 判斷是否重複，觀察哪些資料為 `True`。
3. 使用 `keep=False`，把 `"交易編號"` 有重複的資料**全部標記出來**。
4. 根據 `"交易編號"` 刪除重複資料，重複時**保留第一筆**。
5. 重新建立原始 `df`，這次根據 `"交易編號"` 刪除重複資料，改成**保留最後一筆**。
6. 比較第 4 題與第 5 題的結果，觀察 `keep="first"` 與 `keep="last"` 的差異。

## 練習：學生繳交作業紀錄

老師從系統匯出作業繳交紀錄，但發現部分學生的繳交編號重複。由於無法確定哪一筆才正確，需要進一步找出異常資料。

In [ ]:

import pandas as pd


### 建立作業繳交資料
data = {
    "繳交編號": [
        "H001", "H002", "H003", "H003",
        "H004", "H005", "H005", "H006", "H007"
    ],
    "學生": [
        "小明", "小華", "小美", "小美",
        "阿哲", "小安", "小安", "小宇", "小杰"
    ],
    "分數": [
        85, 72, 90, 95,
        68, 80, 88, 76, 92
    ]
}

df = pd.DataFrame(data)
df

請完成以下任務：

1. 使用 `duplicated()` 檢查**整列資料**是否重複。
2. 改成只根據 `"繳交編號"` 判斷重複資料。
3. 使用 `keep=False`，將所有重複的 `"繳交編號"` 都標記為 `True`。
4. 將第 3 題找到的重複資料實際篩選出來，觀察 `"H003"` 與 `"H005"` 的資料。
5. 假設老師決定：「同一個繳交編號出現多次時，以**最後一次紀錄**為準。」使用 `drop_duplicates()` 清理資料。
6. 現在老師改變規則：「同一個繳交編號只要重複，就無法判斷哪筆正確，因此**整組全部排除**。」使用 `drop_duplicates()` 處理。
7. 完成第 6 題後，確認結果中 `"H003"` 與 `"H005"` 是否已經全部消失。